# Base image:
FROM ruby:2.5.0

ARG API_GATEWAY_DB_ROLE
ARG API_GATEWAY_DB_HOST
ARG API_GATEWAY_DB_PASSWORD
ARG API_GATEWAY_SECRET_KEY
ARG API_GATEWAY_NAME

ENV API_GATEWAY_DB_ROLE=$API_GATEWAY_DB_ROLE
ENV API_GATEWAY_DB_HOST=$API_GATEWAY_DB_HOST
ENV API_GATEWAY_DB_PASSWORD=$API_GATEWAY_DB_PASSWORD
ENV API_GATEWAY_SECRET_KEY=$API_GATEWAY_SECRET_KEY
ENV API_GATEWAY_NAME=$API_GATEWAY_NAME

ENV DEBIAN_FRONTEND noninteractive

# Install dependencies
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev nodejs

RUN mkdir /api_gateway
WORKDIR /$api_gateway

# Gems:
COPY . .
RUN gem install bundler --pre && bundle install --jobs 20 --retry 5

# Copy the main application.

EXPOSE 3001

COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

# The default command that gets ran will be to start the Puma server.
CMD ["bundle", "exec", "puma", "-C", "config/puma.rb"]
